# Generated by Django 5.2.1 on 2026-02-10 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('numero', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Número de Ficha')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='programas.programa')),
            ],
        ),
    ]
