# Generated by Django 5.2.1 on 2026-02-12 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número de Ficha')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio Lectiva')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin Lectiva')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programas.programa', verbose_name='Programa de Formación')),
            ],
        ),
    ]
