# Generated by Django 5.2.1 on 2026-02-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Código del Programa')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Programa')),
            ],
        ),
    ]
