# Generated by Django 5.2.1 on 2026-02-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Programa')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código del Programa')),
                ('nivel', models.CharField(choices=[('Tecnico', 'Técnico'), ('Tecnologo', 'Tecnólogo'), ('Especializacion', 'Especialización')], default='Tecnologo', max_length=20)),
            ],
        ),
    ]
