# Generated by Django 5.2.1 on 2026-03-11 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fichas', '0001_initial'),
        ('programas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PEP', 'PEP')], default='CC', max_length=5)),
                ('documento', models.CharField(max_length=20, verbose_name='Número de identificación')),
                ('telefono', models.CharField(max_length=20, verbose_name='Contacto telefónico')),
                ('correo_personal', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico personal')),
                ('direccion_residencia', models.CharField(blank=True, max_length=200, null=True)),
                ('modalidad_formacion', models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual'), ('A distancia', 'A distancia')], default='Presencial', max_length=50)),
                ('modalidad_etapa', models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual')], default='Presencial', max_length=50, verbose_name='Modalidad etapa productiva')),
                ('etapa_exterior', models.BooleanField(default=False, verbose_name='¿Realiza etapa en el exterior?')),
                ('pais_etapa', models.CharField(default='Colombia', max_length=100, verbose_name='País donde realiza la etapa')),
                ('numero_ficha', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fichas.ficha', verbose_name='Número de grupo')),
                ('programa_formacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='programas.programa', verbose_name='Programa de formación')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
