# Generated by Django 5.2.1 on 2026-02-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprendiz',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Documento de Identidad'),
        ),
    ]
