# Generated by Django 5.2.1 on 2026-03-11 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aprendiz',
            name='programa_formacion',
        ),
    ]
