# Generated by Django 6.0.3 on 2026-03-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0002_remove_aprendiz_programa_formacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprendiz',
            name='empresa',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Empresa donde realiza la etapa'),
        ),
    ]
