# Generated by Django 5.2.1 on 2026-03-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0002_remove_aprendiz_programa_formacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprendiz',
            name='ciudad_municipio',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ciudad / Municipio'),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='departamento',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Departamento'),
        ),
    ]
