# Generated by Django 5.2.1 on 2026-02-18 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0002_aprendiz_documento'),
        ('fichas', '0001_initial'),
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='numero_ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fichas.ficha', verbose_name='Número de Ficha'),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='programa_formacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='programas.programa', verbose_name='Programa de Formación'),
        ),
    ]
