# Generated by Django 5.2.1 on 2026-02-19 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0003_alter_aprendiz_numero_ficha_and_more'),
        ('fichas', '0001_initial'),
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprendiz',
            name='correo_personal',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico personal'),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='direccion_residencia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='etapa_exterior',
            field=models.BooleanField(default=False, verbose_name='¿Realiza etapa en el exterior?'),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='modalidad_etapa',
            field=models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual')], default='Presencial', max_length=50, verbose_name='Modalidad etapa productiva'),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='modalidad_formacion',
            field=models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual'), ('A distancia', 'A distancia')], default='Presencial', max_length=50),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='pais_etapa',
            field=models.CharField(default='Colombia', max_length=100, verbose_name='País donde realiza la etapa'),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PEP', 'PEP')], default='CC', max_length=5),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='documento',
            field=models.CharField(default='0000', max_length=20, verbose_name='Número de identificación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='numero_ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fichas.ficha', verbose_name='Número de grupo'),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='programa_formacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='programas.programa', verbose_name='Programa de formación'),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Contacto telefónico'),
        ),
    ]
