# Generated by Django 5.2.1 on 2026-02-16 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bitacoras', '0002_alter_actividadbitacora_evidencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción de la actividad')),
                ('evidencia', models.CharField(max_length=255, verbose_name='Producto o Evidencia')),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_actividades', to='bitacoras.bitacora')),
            ],
        ),
    ]
