# Generated by Django 5.2.1 on 2026-03-22 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('bitacora_nueva', 'Nueva Bitácora'), ('bitacora_evaluada', 'Bitácora Evaluada'), ('alerta_sistema', 'Alerta del Sistema')], default='alerta_sistema', max_length=50)),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('enlace', models.CharField(blank=True, help_text='URL a la que llevará al hacer clic', max_length=255, null=True)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
