# Generated by Django 5.2.1 on 2026-01-07 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bitacora',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='aprendiz',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='empresa',
        ),
        migrations.DeleteModel(
            name='ActividadBitacora',
        ),
        migrations.DeleteModel(
            name='Bitacora',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
