# Generated by Django 5.2.1 on 2026-01-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='documento',
            field=models.CharField(blank=True, help_text='Número de documento de identidad', max_length=20, null=True, unique=True),
        ),
    ]
