# Generated by Django 5.2.1 on 2026-03-11 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aprendices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion_informacion', models.CharField(choices=[('Pública', 'Pública'), ('Pública Clasificada', 'Pública Clasificada'), ('Pública Reservada', 'Pública Reservada')], default='Pública', max_length=50)),
                ('numero_bitacora', models.PositiveIntegerField(verbose_name='Bitácora N°')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('nombre_completo_aprendiz', models.CharField(max_length=150)),
                ('tipo_documento_aprendiz', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería')], max_length=5)),
                ('numero_identificacion_aprendiz', models.CharField(max_length=20)),
                ('contacto_telefonico_aprendiz', models.CharField(max_length=20)),
                ('correo_institucional_aprendiz', models.EmailField(max_length=254)),
                ('correo_personal_aprendiz', models.EmailField(max_length=254)),
                ('direccion_residencia_aprendiz', models.CharField(max_length=200)),
                ('numero_grupo_ficha', models.CharField(max_length=50)),
                ('modalidad_formacion', models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual'), ('A distancia', 'A distancia')], max_length=50)),
                ('programa_formacion', models.CharField(max_length=150)),
                ('modalidad_ejecucion', models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual'), ('Mixta', 'Mixta')], max_length=20)),
                ('exterior', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2)),
                ('pais_etapa', models.CharField(max_length=100)),
                ('alternativa_etapa', models.CharField(choices=[('Contrato de aprendizaje', 'Contrato de aprendizaje'), ('Vínculo laboral', 'Vínculo laboral'), ('Proyecto productivo', 'Proyecto productivo'), ('Monitoria', 'Monitoria'), ('Apoyo a entidad estatal/ONG', 'Apoyo a entidad estatal/ONG'), ('Asesoría a PYMES', 'Asesoría a PYMES'), ('Pasantía', 'Pasantía')], max_length=100)),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('nit_empresa', models.CharField(max_length=50)),
                ('direccion_empresa', models.CharField(max_length=200)),
                ('nombre_jefe', models.CharField(max_length=150)),
                ('cargo_jefe', models.CharField(max_length=100)),
                ('telefono_jefe', models.CharField(max_length=20)),
                ('email_jefe', models.EmailField(max_length=254)),
                ('nombre_instructor_seguimiento', models.CharField(max_length=150)),
                ('email_instructor_seguimiento', models.EmailField(max_length=254)),
                ('telefono_instructor_seguimiento', models.CharField(blank=True, max_length=20, null=True)),
                ('arl_afiliado', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2)),
                ('nivel_riesgo', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2)),
                ('riesgo_corresponde', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2)),
                ('cuenta_epp', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('NA', 'No Aplica')], max_length=3)),
                ('anexo_fotografico', models.ImageField(blank=True, null=True, upload_to='anexos_bitacoras/')),
                ('firma_aprendiz', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('firma_jefe', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('firma_instructor', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Evaluada', 'Evaluada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20)),
                ('fecha_entrega_bitacora', models.DateField(auto_now_add=True)),
                ('aprendiz_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aprendices.aprendiz')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_actividad', models.TextField()),
                ('competencias_asociadas', models.TextField()),
                ('periodo_mes', models.CharField(max_length=50)),
                ('evidencia_cumplimiento', models.CharField(max_length=255)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='bitacoras.bitacora')),
            ],
        ),
    ]
