# Generated by Django 5.2.1 on 2026-02-12 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aprendices', '0002_aprendiz_documento'),
        ('fichas', '0001_initial'),
        ('instructores', '0002_instructor_cedula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bitacora', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Bitácora')),
                ('fecha_inicio', models.DateField(verbose_name='Período: Desde')),
                ('fecha_fin', models.DateField(verbose_name='Período: Hasta')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería')], default='CC', max_length=2)),
                ('razon_social_empresa', models.CharField(max_length=200, verbose_name='Nombre de la Empresa')),
                ('nit_empresa', models.CharField(max_length=20, verbose_name='NIT')),
                ('direccion_empresa', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('nombre_jefe', models.CharField(max_length=150, verbose_name='Nombre Jefe Inmediato')),
                ('cargo_jefe', models.CharField(max_length=100, verbose_name='Cargo')),
                ('telefono_jefe', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email_jefe', models.EmailField(max_length=254, verbose_name='Email')),
                ('modalidad', models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual'), ('Mixta', 'Mixta')], default='Presencial', max_length=20)),
                ('pais_etapa', models.CharField(default='Colombia', max_length=50)),
                ('afiliado_arl', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('NA', 'No Aplica')], max_length=2, verbose_name='¿Afiliado a ARL?')),
                ('nivel_riesgo', models.CharField(choices=[('I', 'I - Riesgo Mínimo'), ('II', 'II - Riesgo Bajo'), ('III', 'III - Riesgo Medio'), ('IV', 'IV - Riesgo Alto'), ('V', 'V - Riesgo Máximo')], max_length=3, verbose_name='Nivel de Riesgo')),
                ('uso_epp', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('NA', 'No Aplica')], max_length=3, verbose_name='¿Cuenta con EPP?')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Evaluada', 'Evaluada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('observaciones_instructor', models.TextField(blank=True, null=True)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aprendices.aprendiz')),
                ('ficha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fichas.ficha', verbose_name='Ficha de Caracterización')),
                ('instructor_seguimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras_seguimiento', to='instructores.instructor', verbose_name='Instructor de Seguimiento')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción de la actividad')),
                ('fecha_ejecucion', models.DateField(verbose_name='Fecha de Ejecución')),
                ('evidencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Evidencia / Producto')),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='bitacoras.bitacora')),
            ],
        ),
    ]
