# Generated by Django 5.2.1 on 2026-01-25 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Bitácora N°')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio del Período')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin del Período')),
                ('modalidad', models.CharField(choices=[('CA', 'Contrato de Aprendizaje'), ('VL', 'Vínculo Laboral'), ('PP', 'Proyecto Productivo'), ('PA', 'Pasantía'), ('MO', 'Monitoría')], default='CA', max_length=2)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('firmado_jefe', models.BooleanField(default=False, verbose_name='Aprobado por Empresa')),
                ('evaluado_instructor', models.BooleanField(default=False, verbose_name='Evaluado por Instructor')),
                ('observaciones_instructor', models.TextField(blank=True, null=True)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa', verbose_name='Empresa donde realiza prácticas')),
            ],
            options={
                'ordering': ['-numero'],
                'unique_together': {('aprendiz', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ActividadBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción de la actividad')),
                ('fecha_ejecucion', models.DateField(verbose_name='Fecha de ejecución')),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='evidencias/', verbose_name='Evidencia (Archivo/Foto)')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='bitacoras.bitacora')),
            ],
        ),
    ]
