# Generated by Django 5.2.1 on 2026-03-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacoras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadbitacora',
            name='evidencia_cumplimiento',
            field=models.FileField(max_length=255, upload_to=''),
        ),
    ]
