# Generated by Django 5.2.1 on 2026-01-25 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0001_initial'),
        ('bitacoras', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadbitacora',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to='evidencias/', verbose_name='Evidencia'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='aprendiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to='aprendices.aprendiz'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='fecha_fin',
            field=models.DateField(verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha Inicio'),
        ),
    ]
