# Generated by Django 5.2.1 on 2026-02-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacoras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadbitacora',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to='evidencias_bitacoras/', verbose_name='Evidencia / Producto'),
        ),
    ]
