# Generated by Django 5.2.1 on 2026-03-26 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitacoras', '0002_actividadbitacora_fechas_periodo'),
        ('bitacoras', '0002_alter_actividadbitacora_evidencia_cumplimiento'),
    ]

    operations = [
    ]
