# Generated by Django 5.2.1 on 2026-02-10 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0002_aprendiz_documento'),
        ('bitacoras', '0002_alter_actividadbitacora_evidencia_and_more'),
        ('instructores', '0002_instructor_cedula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitacora',
            options={},
        ),
        migrations.RenameField(
            model_name='bitacora',
            old_name='fecha_creacion',
            new_name='fecha_entrega',
        ),
        migrations.AlterUniqueTogether(
            name='bitacora',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='afiliado_arl',
            field=models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='SI', max_length=2, verbose_name='¿Afiliado a ARL?'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='archivo_evidencia',
            field=models.FileField(blank=True, null=True, upload_to='bitacoras/', verbose_name='Evidencia (PDF/Foto)'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='cargo_jefe',
            field=models.CharField(default='Pendiente', max_length=100, verbose_name='Cargo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitacora',
            name='descripcion_actividades',
            field=models.TextField(default='Pendiente', verbose_name='Descripción de actividades realizadas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitacora',
            name='direccion_empresa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección de la Empresa'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='email_jefe',
            field=models.EmailField(default='jefe@gmail.com', max_length=254, verbose_name='Email Jefe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitacora',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Evaluada', 'Evaluada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='instructor_seguimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras_seguimiento', to='instructores.instructor', verbose_name='Instructor de Seguimiento'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='nit_empresa',
            field=models.CharField(default='0000', max_length=20, verbose_name='NIT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitacora',
            name='nivel_riesgo',
            field=models.CharField(choices=[('1', 'I - Riesgo Mínimo'), ('2', 'II - Riesgo Bajo'), ('3', 'III - Riesgo Medio'), ('4', 'IV - Riesgo Alto'), ('5', 'V - Riesgo Máximo')], default='0', max_length=1, verbose_name='Nivel de Riesgo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitacora',
            name='nombre_jefe_inmediato',
            field=models.CharField(default='Pendiente', max_length=150, verbose_name='Nombre Jefe Inmediato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitacora',
            name='numero_bitacora',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de Bitácora'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='pais_etapa',
            field=models.CharField(default='Colombia', max_length=50, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='razon_social_empresa',
            field=models.CharField(default='Pendiente', max_length=200, verbose_name='Nombre de la Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitacora',
            name='riesgo_corresponde',
            field=models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='SI', max_length=2, verbose_name='¿Riesgo corresponde a actividades?'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='telefono_jefe',
            field=models.CharField(default='0', max_length=20, verbose_name='Teléfono Jefe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitacora',
            name='uso_epp',
            field=models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('NA', 'No Aplica')], default='SI', max_length=3, verbose_name='¿Cuenta con EPP?'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='aprendiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aprendices.aprendiz'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='fecha_fin',
            field=models.DateField(verbose_name='Período: Hasta'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Período: Desde'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='modalidad',
            field=models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual'), ('Mixta', 'Mixta')], default='Presencial', max_length=20, verbose_name='Modalidad Etapa Productiva'),
        ),
        migrations.DeleteModel(
            name='ActividadBitacora',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='evaluado_instructor',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='firmado_jefe',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='numero',
        ),
    ]
