# Generated by Django 5.2.1 on 2026-02-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacoras', '0002_alter_actividadbitacora_evidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='pais_etapa',
            field=models.CharField(blank=True, default='Colombia', max_length=50, null=True),
        ),
    ]
