# Generated by Django 5.2.1 on 2026-02-27 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacoras', '0003_alter_bitacora_pais_etapa'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.empresa', verbose_name='Empresa (Ente Co-formador)'),
        ),
    ]
