# Generated by Django 5.2.1 on 2026-02-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacoras', '0003_alter_bitacora_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='numero_bitacora',
            field=models.PositiveIntegerField(blank=True, verbose_name='Número de Bitácora'),
        ),
    ]
