# Generated by Django 5.2.1 on 2026-02-27 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitacoras', '0004_bitacora_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacora',
            name='direccion_empresa',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='nit_empresa',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='razon_social_empresa',
        ),
    ]
