# Generated by Django 5.2.1 on 2026-02-12 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacoras', '0004_alter_bitacora_numero_bitacora'),
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitacora',
            old_name='nombre_jefe_inmediato',
            new_name='nombre_jefe',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='archivo_evidencia',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='descripcion_actividades',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='riesgo_corresponde',
        ),
        migrations.AddField(
            model_name='bitacora',
            name='ficha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fichas.ficha', verbose_name='Ficha de Caracterización'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería')], default='CC', max_length=2),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='afiliado_arl',
            field=models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('NA', 'No Aplica')], max_length=2, verbose_name='¿Afiliado a ARL?'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='direccion_empresa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='email_jefe',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='modalidad',
            field=models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual'), ('Mixta', 'Mixta')], default='Presencial', max_length=20),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='nivel_riesgo',
            field=models.CharField(choices=[('I', 'I - Riesgo Mínimo'), ('II', 'II - Riesgo Bajo'), ('III', 'III - Riesgo Medio'), ('IV', 'IV - Riesgo Alto'), ('V', 'V - Riesgo Máximo')], max_length=3, verbose_name='Nivel de Riesgo'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='numero_bitacora',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Bitácora'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='pais_etapa',
            field=models.CharField(default='Colombia', max_length=50),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='telefono_jefe',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='uso_epp',
            field=models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('NA', 'No Aplica')], max_length=3, verbose_name='¿Cuenta con EPP?'),
        ),
        migrations.CreateModel(
            name='ActividadBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción de la actividad')),
                ('fecha_ejecucion', models.DateField(verbose_name='Fecha de Ejecución')),
                ('evidencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Evidencia / Producto')),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='bitacoras.bitacora')),
            ],
        ),
    ]
