# Generated by Django 5.2.1 on 2026-03-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacoras', '0005_remove_bitacora_direccion_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='firma_instructor',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/', verbose_name='Firma del Instructor'),
        ),
    ]
