# Generated by Django 5.2.1 on 2026-03-07 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitacoras', '0006_bitacora_firma_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacora',
            name='tipo_documento',
        ),
    ]
