# Generated by Django 5.2.1 on 2026-01-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('nombre_jefe', models.CharField(max_length=200, verbose_name='Nombre del Jefe Inmediato')),
                ('cargo_jefe', models.CharField(max_length=100, verbose_name='Cargo')),
                ('telefono_jefe', models.CharField(max_length=20, verbose_name='Teléfono de contacto')),
                ('correo_jefe', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
            ],
        ),
    ]
