# Generated by Django 5.2.1 on 2026-01-21 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion', models.CharField(max_length=100, verbose_name='Profesión / Especialidad')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular')),
                ('tipo_contrato', models.CharField(choices=[('PLANTA', 'Planta'), ('CONTRATISTA', 'Contratista')], default='CONTRATISTA', max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
