# Generated by Django 5.2.1 on 2026-03-11 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PEP', 'PEP'), ('PAS', 'Pasaporte')], default='CC', max_length=5, verbose_name='Tipo de documento')),
                ('correo_personal', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico personal')),
                ('direccion_residencia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección de residencia')),
                ('cedula', models.CharField(max_length=20, verbose_name='Número de identificación')),
                ('profesion', models.CharField(max_length=100, verbose_name='Profesión / Especialidad')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular')),
                ('tipo_contrato', models.CharField(choices=[('PLANTA', 'Planta'), ('CONTRATISTA', 'Contratista')], default='CONTRATISTA', max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
