# Generated by Django 5.2.1 on 2026-01-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={},
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='telefono',
        ),
        migrations.AddField(
            model_name='instructor',
            name='cedula',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='tipo_contrato',
            field=models.CharField(choices=[('PLANTA', 'Planta'), ('CONTRATISTA', 'Contratista')], default='00000', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instructor',
            name='profesion',
            field=models.CharField(max_length=100),
        ),
    ]
