# Generated by Django 5.2.1 on 2026-02-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='cedula',
            field=models.CharField(default='0000', max_length=20, verbose_name='Cédula de Ciudadanía'),
            preserve_default=False,
        ),
    ]
