# Generated by Django 5.2.1 on 2026-02-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructores', '0002_instructor_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='correo_personal',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico personal'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='direccion_residencia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección de residencia'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PEP', 'PEP'), ('PAS', 'Pasaporte')], default='CC', max_length=5, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='cedula',
            field=models.CharField(max_length=20, verbose_name='Número de identificación'),
        ),
    ]
